### ISSUE TITLE
Recursive calling of kernel functions

### ISSUE THREAD

**Issue by Clouckyty** [fatlipp/cuda-tree#2]
Is it correct to recursively call the OctreeKernel function in the OctreeKernel function?

**Comment by fatlipp** [comment]
Yes, it is called CUDA Dynamic Parallelism. 

The idea of dividing the data into non-intersecting subdivisions (4 subdivisions for a quadtree: Top Left, Top Right, Bottom Left, Bottom Right) and allowing each "subkernel" to handle its own partition. And since the data in each block is independent, there is no need to synchronize parallel kernels.
